title: Markus studiert!
email: your-email@domain.com
description: > # Markus Tacker studiert Medieninformatik an der Hochschule RheinMain. 
  In diesem Blog berichtet er Ã¼ber seinen Studienalltag.
baseurl: ""
url: "https://studium.coderbyheart.de"

# Build settings
markdown: kramdown
